import type { Metadata } from "next";
import "./globals.css";
import MainNavbar from "../Components/Navbar/MainNavbar";
import Footer from "@/Components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className="fluent-ui antialiased">
        <MainNavbar />
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
